
SELECT DISTINCT
	AFKO.AUFNR AS 'NR ZLECENIA',
	MATERIALID.MATNR_EXT AS 'NR CZÊŒCI',           
	MAKT.MAKTX AS 'OPIS CZÊŒCI',
	CRHD.SORTB AS 'PLACÓWKA',                            
	AFKO.DISPO AS 'PLANISTA',
	AFKO.GAMNG AS 'ILOSC',
	AFVC.VORNR AS 'NR OPERACJI',
	CRHD2.ARBPL AS 'ST. ROB.',
	CRTX.KTEXT AS 'OPIS ST. ROB.',
	AFKO.FTRMI AS 'DATA ZATW. ZLEC.',
	AFKO.GLTRP AS 'PLAN. ZAK. ZLEC.',
	AFVV.SSEDD AS 'PLAN. ZAK. OP.',
	AFVV.IEDD AS 'RZECZ. ZAK. OP.',
	AFVV.VGW01 AS 'TPZ', 
	AFVV.VGW03 AS 'TJ', 
	CAST(AFVV.VGW01 AS FLOAT) + CAST(AFVV.VGW03 AS FLOAT) * CAST(AFKO.GAMNG AS FLOAT) AS 'CZAS_TECHNOLOGICZNY',
	GODZINY.GODZ_ZAK AS 'CZAS_ZAKONTOWANY', 
	POTW_KONCOWE.PK AS 'POTW_KONCOWE'

FROM 
	[Z_R3_AFKO_TBL] AFKO
	LEFT JOIN [Z_R3_AUFK_TBL] AUFK ON AFKO.AUFNR = AUFK.AUFNR
	LEFT JOIN [Z_R3_AFPO_TBL] AFPO ON AFKO.AUFNR = AFPO.AUFNR
	LEFT JOIN [.[Z_R3_MATERIALID_TBL] MATERIALID ON AFKO.PLNBEZ = MATERIALID.MATNR_INT
	LEFT JOIN [Z_R3_CRHD_TBL] CRHD ON AUFK.ZZARBPL = CRHD.ARBPL
	LEFT JOIN [Z_R3_MAKT_TBL] MAKT ON AFKO.PLNBEZ = MAKT.MATNR 
	LEFT JOIN [Z_R3_AFVC_TBL] AFVC ON AFKO.AUFPL = AFVC.AUFPL
	LEFT JOIN [Z_R3_CRHD_TBL] CRHD2 ON AFVC.ARBID = CRHD2.OBJID
	LEFT JOIN [Z_R3_CRTX_TBL] CRTX ON CRHD2.OBJID = CRTX.OBJID
	LEFT JOIN [Z_R3_AFVV_TBL] AFVV ON AFVC.AUFPL = AFVV.AUFPL AND AFVC.APLZL = AFVV.APLZL

/*AFRU*/
	LEFT JOIN [Z_R3_AFRU_TBL] AFRU ON AFRU.AUFPL = AFVV.AUFPL AND AFRU.APLZL = AFVV.APLZL
	LEFT JOIN 
			(SELECT
				CATSDB.RAUFPL AS ZL_KON,
				CATSDB.RAPLZL AS OP_KON,
				SUM(CATSDB.CATSHOURS) AS GODZ_ZAK
			FROM
				[Z_R3_CATSDB_TBL] CATSDB
			GROUP BY
				CATSDB.RAUFPL,
				CATSDB.RAPLZL
			) GODZINY ON AFKO.AUFPL = ZL_KON AND AFVC.APLZL = OP_KON
	/*KONTOWANIA-CATSDB*/
	--LEFT JOIN 
	--		(
	--		SELECT DISTINCT
	--			POTW.RAUFPL AS ZK,
	--			POTW.RAPLZL AS OK,
	--			POTW.AUERU AS PK
	--		FROM
	--			[Z_R3_CATSDB_TBL] POTW
	--		WHERE
	--			POTW.AUERU = 'X'
	--		) POTW_KONCOWE ON AFKO.AUFPL = ZK AND AFVC.APLZL = OK
	/*POTWIERDZENIA-AFRU*/
	LEFT JOIN 
			(
			SELECT DISTINCT
				POTW.AUFPL AS ZK,
				POTW.APLZL AS OK,
				POTW.AUERU AS PK
			FROM
				[Z_R3_AFRU_TBL] POTW
			WHERE
				POTW.AUERU = 'X'
			) POTW_KONCOWE ON AFKO.AUFPL = ZK AND AFVC.APLZL = OK

WHERE 
	--AFPO.DNREL IS NULL AND 
	--AFPO.ELIKZ IS NULL AND 
	CRHD.CPLGR = 'W30' AND
	MAKT.SPRAS = 'L' AND
	CRTX.SPRAS = 'L' AND 
	AFKO.AUFNR = '007202623837'

ORDER BY 
	AFKO.AUFNR, 
	AFVC.VORNR

