SELECT DISTINCT  
		CATSDB.PERNR AS Nr_osobowy,
		PLACOWKA_PRACOWNIK.NAZWISKO AS Nazwisko_i_Imie, 
		PLACOWKA_PRACOWNIK.PLACÓWKA AS Placowka, 
		CONVERT(VARCHAR(10), CATSDB.WORKDATE, 120) AS Data_kontowania, 
		CATSDB.SKOSTL AS MPK, 
		CATSDB.LSTAR AS LSTAR, 
		CATSDB.RAUFNR AS Nr_zlecenia, 
		CATSDB.EXTAPPLICATION AS Nr_operacji, 
		MATERIALID.MATNR_EXT AS Nr_czesci, 
		CRHD.ARBPL AS Stanowisko,
		CATSDB.AWART AS AWART, 
		AUFK.ZZMATNR_LO, 
		AUFK.ZZSERNR_LO, 
		CAST(SUM(CATSDB.CATSHOURS) AS FLOAT) AS Godziny 

FROM [Z_R3_CATSDB_TBL] CATSDB
	LEFT OUTER JOIN [Z_R3_AFVC_TBL] AFVC ON CATSDB.RAUFPL = AFVC.AUFPL AND CATSDB.EXTAPPLICATION = AFVC.VORNR
	LEFT OUTER JOIN [Z_R3_CRHD_TBL] CRHD ON AFVC.ARBID = CRHD.OBJID

	/*nr części*/
	LEFT OUTER JOIN [Z_R3_AFKO_TBL] AFKO ON CATSDB.RAUFPL = AFKO.AUFPL
	LEFT OUTER JOIN [[Z_R3_MATERIALID_TBL] MATERIALID ON AFKO.PLNBEZ = MATERIALID.MATNR_INT
	
	LEFT JOIN [Z_R3_AUFK_TBL] AUFK ON CATSDB.RAUFNR = AUFK.AUFNR
	
	LEFT OUTER JOIN (
		SELECT DISTINCT
			NI.PERNR AS NR_ZNACZKA, 
			NI.SNAME AS NAZWISKO, 
			NI.MSTBR AS PRZEŁOŻONY, 
			EMPLY.PROD_REP_DESC AS PLACÓWKA
		FROM
			[Z_R3_PA0001_TBL] NI
			LEFT JOIN Z_SOL_SACC_EMPLY_HIERARCHY_TBL EMPLY ON NI.MSTBR = EMPLY.EMPLID
			LEFT JOIN (
			SELECT DISTINCT
				NI.PERNR AS NR_ZNACZKA,
				MAX(NI.ENDDA) AS DATA
			FROM
				[Z_R3_PA0001_TBL] NI
			GROUP BY
				NI.PERNR		
			) MAX_DATA ON NI.PERNR = MAX_DATA.NR_ZNACZKA
		WHERE
			NI.PERNR = MAX_DATA.NR_ZNACZKA 
			AND NI.ENDDA = MAX_DATA.DATA
		) PLACOWKA_PRACOWNIK ON CATSDB.PERNR = PLACOWKA_PRACOWNIK.NR_ZNACZKA 

WHERE 
	WORKDATE BETWEEN '2021-09-01' AND '2023-12-19'
	AND (CATSDB.SKOSTL = '0000001321' 
		OR CATSDB.SKOSTL = '0000001380'
		OR CATSDB.SKOSTL = '1303C' 
		OR CATSDB.SKOSTL = '1303D' 
		OR CATSDB.SKOSTL = '0000001300' 

	--AND CRHD.ARBPL = 'M135'

GROUP BY
	CATSDB.PERNR, 
	PLACOWKA_PRACOWNIK.NAZWISKO, 
	PLACOWKA_PRACOWNIK.PLACÓWKA, 
	CATSDB.WORKDATE, 
	CATSDB.SKOSTL, 
	CATSDB.LSTAR, 
	CATSDB.RAUFNR, 
	CATSDB.EXTAPPLICATION, 
	MATERIALID.MATNR_EXT, 
	CRHD.ARBPL, 
	CATSDB.AWART, 
	AUFK.ZZMATNR_LO, 
	AUFK.ZZSERNR_LO
	
ORDER BY
	Data_kontowania
